# Dockerfile
# Stage 1: build
FROM node:20-alpine AS builder
WORKDIR /app

# Copy package.json và install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build project
RUN npm run build

# Stage 2: run
FROM node:20-alpine
WORKDIR /app

# Copy node_modules và build output
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

# Set environment variables if needed
ENV NODE_ENV=production

# Expose port
EXPOSE 4001

# Command to run the app
CMD ["node", "dist/main.js"]